name: inter_knot
description: 绳网是一个游戏、技术交流平台
publish_to: none
version: 2.16.9+36
repository: https://github.com/share121/inter_knot

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  dart_jsonwebtoken: ^3.3.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  flutter_quill: ^11.5.0
  flutter_widget_from_html: ^0.17.1
  fwfh_svg: ^0.16.1
  fwfh_url_launcher: ^0.16.1
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.4.0
  markdown: ^7.3.0
  markdown_quill: ^4.3.0
  material_design_icons_flutter: ^7.0.7296
  pub_semver: ^2.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  vsc_quill_delta_to_html: ^1.0.5
  waterfall_flow: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: icon.webp
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ZhCn
      fonts:
        - asset: assets/fonts/zh-cn.ttf

msix_config:
  display_name: 绳网
  publisher_display_name: share121
  identity_name: com.share121.inter-knot
  msix_version: 1.0.0.0
  logo_path: icon.webp
  capabilities: internetClient
  languages: zh-CN, zh-TC, en-US
