name: Manual Web Package

on:
  workflow_dispatch:

env:
  PEM: ${{ secrets.PEM }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  PUB_UPGRADE_REPORT: none

jobs:
  build_web:
    name: Web Client (Manual)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: dart gen_secrets.dart

      - name: Flutter Pub Get (Silent)
        run: flutter pub get --suppress-analytics >/dev/null 2>&1

      - run: flutter build web --no-wasm-dry-run --suppress-analytics

      - run: echo "db97e0128d9a02eef17b05a3c3ff8691742e6ab3" > build/web/12e2a2a7bc7f973a3f3720dcd9bb923b.txt

      - run: gzip -rk9 build/web

      - uses: actions/upload-artifact@v4
        with:
          name: inter_knot_web
          path: build/web
